# ORION CARLA数据集训练配置

experiment_name: "orion_carla"
dataset_type: "carla"
data_path: "data/carla/"

# CARLA专用设置
image_size: [256, 256]
sequence_length: 16

# 大型模型配置
vision:
  backbone: "resnet50"
  pretrained: true
  output_dim: 1024
  frozen_layers: 2

qt_former:
  vision_dim: 1024
  token_dim: 768
  num_history_queries: 16
  memory_size: 128
  num_layers: 3

llm:
  model_type: "gpt2"  # 或使用更大的模型
  token_dim: 768
  num_layers: 4
  hidden_dim: 3072
  vqa_classes: 32

planner:
  token_dim: 768
  traj_len: 30
  hidden_dim: 1024
  latent_dim: 128
  num_layers: 4

# 训练设置
training:
  epochs: 200
  batch_size: 16
  learning_rate: 1e-4
  weight_decay: 1e-4
  warmup_steps: 2000
  gradient_clip_norm: 0.5
  
  # 更频繁的验证和保存
  eval_every: 500
  save_every: 2000
  keep_checkpoints: 10
  
  # 损失权重调整
  vqa_weight: 0.2
  trajectory_weight: 1.0
  temporal_consistency_weight: 0.1

# 设备优化
device: "cuda"
mixed_precision: true
compile_model: true
num_workers: 8
