# ORION默认配置文件

# 实验设置
experiment_name: "orion_default"
output_dir: "outputs/"
checkpoint_dir: "checkpoints/"
log_dir: "logs/"
seed: 42

# 数据设置
data_path: "data/"
dataset_type: "toy"  # toy, carla, nuscenes
image_size: [224, 224]
sequence_length: 8

# 设备设置
device: "auto"  # auto, cpu, cuda
mixed_precision: true
compile_model: false
num_workers: 4
pin_memory: true

# 视觉编码器配置
vision:
  backbone: "resnet18"  # resnet18, resnet50, efficientnet_b0
  pretrained: true
  output_dim: 512
  frozen_layers: 0
  dropout: 0.1

# QT-Former配置
qt_former:
  vision_dim: 512
  token_dim: 512
  num_history_queries: 8
  memory_size: 64
  num_heads: 8
  num_layers: 2
  dropout: 0.1
  memory_update_rate: 0.1

# LLM配置
llm:
  model_type: "toy"  # toy, gpt2, llama
  model_name: null  # HuggingFace模型名（如果使用）
  token_dim: 512
  num_layers: 2
  num_heads: 8
  hidden_dim: 2048
  vqa_classes: 16
  max_sequence_length: 256
  dropout: 0.1
  use_cache: true

# 生成式规划器配置
planner:
  token_dim: 512
  traj_len: 20
  hidden_dim: 512
  latent_dim: 64
  num_layers: 3
  dropout: 0.1
  beta_kl: 0.001
  align_weight: 0.1
  diversity_weight: 0.05

# 训练配置
training:
  # 基础参数
  epochs: 100
  batch_size: 8
  learning_rate: 2e-4
  weight_decay: 1e-5
  warmup_steps: 1000
  
  # 学习率调度
  scheduler: "cosine"  # cosine, linear, exponential
  min_lr: 1e-6
  
  # 优化器
  optimizer: "adamw"  # adamw, adam, sgd
  betas: [0.9, 0.999]
  eps: 1e-8
  
  # 梯度处理
  gradient_clip_norm: 1.0
  accumulation_steps: 1
  
  # 损失权重
  vqa_weight: 0.1
  trajectory_weight: 1.0
  temporal_consistency_weight: 0.05
  
  # 验证和保存
  eval_every: 1000
  save_every: 5000
  keep_checkpoints: 5
  
  # 早停
  early_stopping: true
  patience: 10
  min_delta: 1e-4
