# ORION玩具数据集快速训练配置

# 继承默认配置并修改部分参数
experiment_name: "orion_toy_quick"
dataset_type: "toy"

# 快速训练设置
training:
  epochs: 5
  batch_size: 4
  learning_rate: 1e-3
  eval_every: 100
  save_every: 500
  
# 小型模型配置（用于快速测试）
vision:
  backbone: "resnet18"
  output_dim: 256

qt_former:
  vision_dim: 256
  token_dim: 256
  num_history_queries: 4
  memory_size: 32
  num_layers: 1

llm:
  token_dim: 256
  num_layers: 1
  hidden_dim: 512
  vqa_classes: 8

planner:
  token_dim: 256
  traj_len: 10
  hidden_dim: 256
  latent_dim: 32
  num_layers: 2
